---
- hosts: 172.31.34.33
  become: yes
  tasks:
  - include_tasks: myfile.yml
  
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy file into ansible node side
    copy:
      src: mystaticfile.txt
      dest: /home/ubuntu/mystaticfile.txt


  - name: coupy index.j2 file into ansible node side
    template:
        src:  myindex.j2
        dest: /var/www/html/index.html


  - name: download interbet file
    ansible.builtin.get_url:
    url: https://get.jenkins.io/war-stable/2.375.1/jenkins.war
    dest: /home/ubuntu/jenkins.war

