---
- hosts: 172.31.34.33
  become: yes
  tasks:
  - include_tasks: myfile.yml
  
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy file into ansible node side
    copy:
      src: mystaticfile.txt
      dest: /home/ubuntu/mystaticfile.txt