---
- hosts: 172.31.34.33
  become: yes
  tasks:
  - name: I want to execute linux command
    command: hostname -f
    register: myresult

  - name: I want to diaplys my first task result
    debug:
       msg: "{{myresult}}"

  - name: install git
    apt: 
      name: git
      state: present
    when: myresult.stderr !=""

  - name: install tree
    apt:
      name: tree
      state: present
    when: myresult.stderr ==""