---
- hosts: 172.31.34.33
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      state: present

  - name: install tree
    apt:
      name: tree
      stateee: present
    ignore_errors: true

  - name: install wget
    apt:
      name: wget
      state: present 