---
- hosts: myWebServers
  become: yes
  tasks:
  - name: I want to install weberver on ubuntu ansible nodes
    apt:
      name: "{{webpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: I want to start webserver on ubuntu ansible node
    service:
      name: apache2
      state: restarted
    when: ansible_os_family =="Debian"

  - name: I want to install webserver on RedHat ansible nodes
    yum: 
      name: "{{webpackonubuntu}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: I want to start weberver on RedHat ansible nodes
    service:
      name: httpd
      state: started
    when: ansible_os_family =="RedHat"